### ISSUE TITLE
UI: AI answer extra copy table button

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#112]
Add a button to copy table exclusively and copy HTML representation, not md

Make copy button to copy HTML and another button to copy original answer.

[Original Issue in Trello](https://trello.com/c/m6udMqD1/443-ui-ai-answer-extra-copy-table-button)

**Comment by arozumenko** [comment]
@liana-gif  check if it is actual

**Comment by epamLDadayan** [comment]
@liana-gif , @arozumenko 

This is fixed and implemented.
