### ISSUE TITLE
Issues with Filtering types (Page Id and Space Name) for Confluence source type datasets

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#116]
Confluence source type for Datasets (Datasource). When we are trying to filter either by Space name or page id. Getting "Internal Server Error" in the logs. 

Only Filtering by label is working.  Checked on EYE env.[2a1a0296-d2c5-4fcd-8245-29e86002f121.log](https://trello.com/1/cards/66718b8d55169db62d74cb69/attachments/66718ba5c963a4c6c66405fb/download/2a1a0296-d2c5-4fcd-8245-29e86002f121.log "‌")

[Original Issue in Trello](https://trello.com/c/DbPN3PI1/499-issues-with-filtering-types-page-id-and-space-name-for-confluence-source-type-datasets)

![Image](https://trello.com/1/cards/66718b8d55169db62d74cb69/attachments/66718ba5c963a4c6c66405fb/download/2a1a0296-d2c5-4fcd-8245-29e86002f121.log)

**Comment by epamLDadayan** [comment]
Duplicate bug. The issue for Space is fixed. We have a separate bug for Page ID
