### ISSUE TITLE
An error occurs when attaching an Excel file with multiple sheets to the dataset creation process.

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#121]
An error occurs when attempting to attach an Excel file containing multiple sheets to the dataset creation process. The system fails to process the file, resulting in a dataset update error.

**Precondition:**

User on the MyLybraries/Datasource creation page.

**Env:**

Win 11, Google Chrome, beta env.

**Steps to reproduce:**

1. Select the option to add a new table as a source type.
2. Choose an Excel file that contains multiple sheets (e.g., RADAR Positions Dashboard 2024-06-18 20-16_new.xlsx).
3. Click create

**Actual result:**

An error message appears: An error occurred during dataset creation. Functionality related to the embedded content may be impacted.

**Expected result:**

The Excel file is successfully attached, and the data is processed without errors.

![image.png](https://trello.com/1/cards/66746b9a0d63efbec63201c5/attachments/66746cd4f789c7adf68ff721/download/image.png)

[Original Issue in Trello](https://trello.com/c/Xm0hxylw/502-an-error-occurs-when-attaching-an-excel-file-with-multiple-sheets-to-the-dataset-creation-process)

![Image](https://trello.com/1/cards/66746b9a0d63efbec63201c5/attachments/66746cd4f789c7adf68ff721/download/image.png)

**Comment by epamLDadayan** [comment]
NOT AN ISSUE, but incorrect configuration - Raw content option must be selected in this scenario.
