### ISSUE TITLE
Internal Sever error while uploading JSON file for datsourse table source type

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#122]
When attempting to upload a JSON file for the datasource table source type, the system returns an "Internal Server Error".

**Env:**

Win 11, Google Chrome, beta env.

**Preconditions:**

- User is on the "My libraries/Datasource" page.
- Datasource is created without adding a file.

**Steps to reproduce:**

1. Click + to add file
2. provide name, add source type=Table, attache Json file
3. Click create

**Actual result:**

An "Internal Server Error" message is displayed, and the JSON file upload fails.

**Expected result:**

The JSON file should be successfully uploaded.

[Original Issue in Trello](https://trello.com/c/Agvoopd9/514-internal-sever-error-while-uploading-json-file-for-datsourse-table-source-type)

**Comment by epamLDadayan** [comment]
NOT A BUG, For json file - File type must be selected rather than Table.
