### ISSUE TITLE
"Change View" button is not visible when the window width is less than ~ a page-half

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#123]
"Change View" button (Card/Detailed View) is not visible when the window width is less than ~ a page-half

**Env:** Win 11, Microsoft Edge, Beta env: [https://eye.projectalita.ai/](https://eye.projectalita.ai/ "‌")

**Precondition:**

- User is on the "My libraries" page

**Steps to reproduce:**

1. Open "All" Tab
2. Click on the "Card View" icon
3. Change browser window size, e.g. the window width is changed to around a page-half or less.
4. Verify "Card View" layout
5. Switch between different Tabs of the page
6. Verify "Card View" layout

**Actual result:**

"Change View" button is not visible when the window width is less than ~ a page-half

**Expected result:**

(Feature request)

When the window's width is changed to ~ a page-half or less, then the Menu (with the "Change View" button and other Tabs like e.g. Collections, Agents, etc.) is adjusted accordingly, so that a user could see them and click if needed.

![image.png](https://trello.com/1/cards/668a56f0b7b21e37e3c3de9b/attachments/668a581694dde894d5cb6610/download/image.png)

[Original Issue in Trello](https://trello.com/c/KwH520tq/516-change-view-button-is-not-visible-when-the-window-width-is-less-than-a-page-half)

![Image](https://trello.com/1/cards/668a56f0b7b21e37e3c3de9b/attachments/668a581694dde894d5cb6610/download/image.png)

**Comment by epamLDadayan** [comment]
You need to make the size of screen too small (1000x550px) to hide the Card and Table views and you can horizontally scroll tabs to see the icons. This is currently applicable for Prompts menu.
Can be closed for now.
