### ISSUE TITLE
Sorting By Authors: Selected Sorting is Not persisted, when switching to "My Liked" and "Trending" Tabs from other Tab

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#124]
Verify sorting By Authors: Selected Sorting is Not persisted, when switching to "My Liked" and "Trending" Tabs from other Tab (like it works in My Libraries)

**Env:** Win 11, Microsoft Edge, Beta env: [https://eye.projectalita.ai/](https://eye.projectalita.ai/ "‌")

**Preconditions:**

- User is on the "Prompts" page
- "Latest" Tab is opened
- At least several elements are added
- Detailed View" is displayed (selected)

**Steps to reproduce:**

1. Click on the "Authors" sorting option (Asc).
2. Click on the "Authors" sorting option (Desc).
3. Switch to the "My Liked" Tab
4. Click on the "Authors" sorting option (Asc).
5. Switch to the "Trending" Tab

**Actual result:**

1. Selected Sorting is Not persisted, when switching to "My Liked" Tab from other Tab (like it works in My Libraries)

5\. Selected Sorting is Not persisted, when switching to "Trending" Tab from other Tab

**Expected result:**

3\.Selected Sorting is persisted

5\.Selected Sorting is persisted

(like it currently works in My Libraries)

[Original Issue in Trello](https://trello.com/c/v7gybJYu/518-sorting-by-authors-selected-sorting-is-not-persisted-when-switching-to-my-liked-and-trending-tabs-from-other-tab)

**Comment by epamLDadayan** [comment]
@arozumenko , @liana-gif 
This issue is still applicable.

**Comment by HawkQing1** [comment]
@arozumenko, after discussion with @Aspect13 , we decided to disable sorting by Authors, because it should be done in BE instead of in FE due to pagination and currently the list APIs have not supported sorting by authors yet.

**Comment by HawkQing1** [comment]
@epamLDadayan we've disabled sorting by Authors, please verify it on main.

**Comment by epamLDadayan** [comment]
Fixed, sorting by Authors is disabled. CHecked on Main env.
