### ISSUE TITLE
Unable to Stup creating/indexing the dataset in the middle of it's creation

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#131]
User unable to stop the dataset creation/indexing while the process has already started.

[Original Issue in Trello](https://trello.com/c/d0BOCjOH/536-unable-to-stup-creating-indexing-the-dataset-in-the-middle-of-its-creation)

**Comment by epamLDadayan** [comment]
Tested on EYE and Main envs.
