### ISSUE TITLE
UI: Monitoring rework

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#143]
Monitoring page should look differently now.

1. need to move project selector from navbar to filters panel
2. project select needs to be a separate component and should work more like filter that a project switcher
3. populate project dropdown based on another backend api - it will return projects and project groups that are available to the user. Dropdown is single select + ‘all’ option
4. re-organize filters - they should be in following order:
   1. project filter
   2. date from
   3. date to
   4. type
   5. name
   6. users
5. if project filter has 1 project selected - everything is ok, but if ‘all’ or a group - disable filters: type, name, users

[Original Issue in Trello](https://trello.com/c/fcR29EF8/531-ui-monitoring-rework)

**Comment by epamLDadayan** [comment]
Fixed, tested on Prod env.
