### ISSUE TITLE
Unable to Add Public Prompts Without Models to Chat as a Participant

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#147]
**Description:** Users are unable to add public prompts that lack associated models to a chat as a participant. This issue occurs when the model associated with the prompt has been deleted. As a fix, the system should automatically use the next available model, similar to the behavior when importing prompts.

**Steps to Reproduce:**

1. Navigate to the Chat section.
2. Search and select a public prompt that lacks an associated model (e.g., the model has been deleted).
3. Attempt to add the prompt to a chat as a participant.
4. Observe the result.

**Expected Result:** The prompt should be added to the chat using the next available model automatically.

**Actual Result:** The prompt cannot be added to the chat due to the missing model.

![image.png](https://trello.com/1/cards/66c5c5bdbd4ccc0f7d7a4a82/attachments/66c5c5fb19ca1891274d467a/download/image.png)

![image.png](https://trello.com/1/cards/66c5c5bdbd4ccc0f7d7a4a82/attachments/66c5c60744375ba76deafeac/download/image.png)

[Original Issue in Trello](https://trello.com/c/EFSZStA8/532-unable-to-add-public-prompts-without-models-to-chat-as-a-participant)

![Image](https://trello.com/1/cards/66c5c5bdbd4ccc0f7d7a4a82/attachments/66c5c5fb19ca1891274d467a/download/image.png)

![Image](https://trello.com/1/cards/66c5c5bdbd4ccc0f7d7a4a82/attachments/66c5c60744375ba76deafeac/download/image.png)

**Comment by epamLDadayan** [comment]
Fixed, user now can add such prompts and later select/configure a LLM model for it
