### ISSUE TITLE
Switching from Private to Public project, and duplicating the Browser tab with previously opened "Private" Prompt causes error

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#21]
Switching from Private to Public project, and duplicating the Browser tab with previously opened "Private" Prompt causes error
 
### Steps to reproduce:
 
1. Open Private Prompt (my example: "_My Libraries_Prompts_ Save Prompt with Discard Changes").
2. Duplicate the Tab with the opened Private Prompt. > ER=AR=Duplicated Tab 2 with the "Private" Prompt is opened, with the same content.
3. Remaining in the opened Tab 2, navigate to Prompts > Public.
4. Open a Public Prompt.
5. Open a Tab 1 again > from there: Duplicate a Browser Tab.
 
ActR: "No prompt found with id '38' or no version 'latest'" error message is displayed. 
(Looks like the system is looking for this Private Prompt in the Public project)
ExpR: No error message. Duplicated Tab with the "Private" Prompt is opened, with the same content.

**Comment by arozumenko** [comment]
![Image](https://trello.com/1/cards/659e2e59e98f48090e196f92/attachments/659e2e9012c34d67a47e03e1/download/image.png)

**Comment by yulia-snezhko** [comment]
Hi All, 
please find the screenshot attached:
![Image](https://github.com/user-attachments/assets/d91b0191-8df5-4f13-8043-977d7d9e0407)

Thanks!
BR, Yulia

**Comment by HawkQing1** [comment]
@epamLDadayan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Now I am getting another error with the same scenario  @HawkQing1 @epamLDadayan 
![Image](https://github.com/user-attachments/assets/70681353-b8c8-43e2-bf9d-4cdd68b0934d)
