### ISSUE TITLE
[BUG] Mixing title and content of different prompts, while Duplicating Tabs

### ISSUE THREAD

**Issue by yulia-snezhko** [ProjectAlita/projectalita.github.io#471]
QA Env: https://eye.projectalita.ai/alita_ui/prompts/all

Steps to reproduce:
1. Open **Private** Prompt (my example: "Add a record in _On Moderation_ status_v2", Rejected).
2. Duplicate the Tab with the opened Private Prompt. > ER=AR=Duplicated Tab 2 with the "Private" Prompt is opened, with the same content.
3. Remaining in the opened Tab 2, navigate to Prompts > **Public**.
4. Open a Public Prompt. Example of the prompt: "Create User stories using specified template"
5. Open a Tab 1 again (with Private Prompt opened) > from there: Duplicate a Browser Tab.

**ActR**: The Prompt is opened with the mixed content:
- Title of the **Private** prompt
- Context and other content - of the **Public** prompt.

**ExpR**: Duplicated Tab with the "Private" Prompt is opened, with the same content.

![2024-09-03_Mixing title and content of different prompts, while Duplicating Tabs](https://github.com/user-attachments/assets/7eafc808-1061-4f7f-8107-747d13e452b4)

**Comment by epamLDadayan** [comment]
This issue is fixed thanks to other fixes. Now user gets notified that such prompt is not available in Public project.
