### ISSUE TITLE
[BUG] Renamed ELITEA Agent is incorrectly displayed on the Agent View Wizard

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#481]
Steps to reproduce:

1. Create an agent.
2. Share the link to the agent with someone. (E.g., [Some Weird Assistant](https://eye.projectalita.ai/alita_ui/agents/all/3?viewMode=owner&name=Some+Weird+Name)).
3. Rename the agent and save changes.
4. If you open the previously shared link:
    1. The agent will open, because it is found by index 3 in the URL resource path.
    2. The General section contains the correct new name of the agent.

Expected Result:

The header contains the updated agent's name.

Actual Result:

But the header remains unchanged: Agents / Some Weird Assistant.

![Image](https://github.com/user-attachments/assets/1f01bd77-9d55-4390-b737-2b8c2c3f5d33)

Observations:
The reason is that the page header apparently gets its value from the name input parameter of the GET request (supplied by the user), instead of the same source as the Title text box under the General section:
alita_ui/agents/all/3?viewMode=owner&name=Some+Weird+Assistant
If you remove the name from the GET params in the URL, the header will be rendered as even more confusing label:

![Image](https://github.com/user-attachments/assets/a8b3b933-65a7-46f7-9a44-403d69dae92f)

The issue may be relevant to other ELITEA entities that support renaming, but I didn't check.

**Comment by HawkQing1** [comment]
@epamLDadayan I can not reproduce it. Could you please verify it on main?

**Comment by epamLDadayan** [comment]
Fixed, tested on MAIN env. Ready for next Release.
