### ISSUE TITLE
[BUG] Unable to Close Generate Token Page After Switching Projects

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#483]
**Description**: When attempting to generate a token and switching between projects on the Generate Token page, an issue occurs where the user can copy the token but cannot close the Generate Token page. This happens because the user is not in the exact private project but in a mixed state (e.g., Alita AI testing/Private).

**Steps to Reproduce:**

1. Navigate to the Settings→Configuration page on the Alita AI platform, Generate token.
2. Switch between different projects while on the Generate Token page.
3. Generate and copy a token.
4. Attempt to close the Generate Token page.
5. Observe that the page cannot be closed.

**Expected Result**: The user should be able to switch between projects, generate and copy a token, and close the Generate Token page without any issues.

**Actual Result**: After switching between projects and copying the token, the user cannot close the Generate Token page due to being in a mixed project state.

**Additional Information:**

- Issue: Inability to close the Generate Token page after switching projects.
- Reproducibility: Consistently reproducible when switching projects on the Generate Token page.
- Project State: The user ends up in a mixed project state (e.g., Alita AI testing/Private).

**Comment by HawkQing1** [comment]
@epamLDadayan I can not reproduce it on main. Could you please help with this?

**Comment by epamLDadayan** [comment]
Fixed, tested on Main env
