### ISSUE TITLE
[BUG] Unable to Set/Edit Secret Value if Initially Left Empty

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#488]
**Title:** Unable to Set/Edit Secret Value if Initially Left Empty

**Description:**
When creating a new secret and leaving the value field empty initially, it becomes impossible to set or edit the value later. Additionally, the name of the secret cannot be modified after creation, which could be a useful feature.

**Steps to Reproduce:**
1. Create a new secret and provide a name.
2. Click somewhere else on the page without providing a value.
3. Attempt to edit the value and provide it.

**Actual Result:**
The value field becomes non-editable, preventing the user from setting or editing the value.

**Expected Result:**
The user should be able to modify and provide the value even if it was initially left empty. Additionally, the user should be able to modify the name of the secret.

**Notes:**
- It is common for users to click elsewhere on the page or copy the actual value only after creating the name, making it difficult to provide the value immediately.
- Allowing users to modify the name of the secret could be a useful feature.

**Comment by HawkQing1** [comment]
@epamLDadayan, it's fixed, please verify it on main

**Comment by epamLDadayan** [comment]
Fixed, tested on MAIN env. Ready for next Release.
