### ISSUE TITLE
[BUG] Save and Discard Buttons Activated After Executing Search Function in Datasources

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#495]
**Description:**
The Save and Discard buttons become activated and available for clicking after executing the Search function in datasources. These buttons should not be activated or available for clicking after performing a search.

**Steps to Reproduce:**
1. Create a datasource.
2. Create and set up a dataset.
3. Navigate to the Search tab.
4. Select the corresponding embedding model.
5. Enter the text and start the search.
6. Verify whether the Save and Discard buttons become active and available for clicking.

**Actual Result:**
The Save and Discard buttons are activated and become available for clicking after executing the Search function.

**Expected Result:**
The Save and Discard buttons should not be activated or available for clicking after executing the Search function.

**Notes:**
- The activation of the Save and Discard buttons after a search may lead to unintended changes being saved or discarded.
- Ensure that the buttons remain inactive unless there are actual changes to save or discard.

**Comment by HawkQing1** [comment]
@epamLDadayan , Hi Levon, the Save and Discard Buttons are activated due to the user selects/changes embedding modal, should we not save this changes in datasource details?

**Comment by epamLDadayan** [comment]
@HawkQing1 , Let's review it together.

**Comment by epamLDadayan** [comment]
Fixed thanks to other changes and fixes.
