### ISSUE TITLE
[BUG] When creating TestRail toolkit with integration from same project, agent will not respond

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#518]
**Steps to reproduce** 
Go to a project other than Private
Create an integration with test rail 
Go to an agent and create a test rail toolkit using the integration from the project 
![Image](https://github.com/user-attachments/assets/7921efb2-aed1-4cb4-9504-d4643f21a120)
**Actual result** 
The agent will not respond to user messages ( no generation or response will be done) 

**Expected result** 
The agent will respond with the answer

**Comment by SamvelSimonyan** [comment]
Fixed
