### ISSUE TITLE
[BUG] Unable to Modify Password Options for QTest Source Type Dataset

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#523]
**Title:** Unable to Modify Password Options for QTest Source Type Dataset

**Description:**
When attempting to update a dataset with the QTest source type, the authentication options cannot be modified. Specifically, the Secret option is inactive and cannot be selected.

**Steps to Reproduce:**
1. Create a datasource.
2. Add a dataset with QTest type.
3. Create a password for it or leave it empty.
4. Create the dataset.
5. Stop the dataset creation or wait until it completes.
6. Click the update option and try to change the authentication options (e.g., from Password to Secret).

**Actual Result:**
The Secret option is inactive and cannot be selected.

**Expected Result:**
The authentication options should be active, allowing the user to change them.

**Notes:**
- This issue restricts users from updating authentication methods for datasets.
- Ensure that all authentication options are available for modification during updates.
- This is also applicable if you are importing a datasource with QTest dataset

Please investigate and resolve the issue to allow users to modify authentication options for QTest source type datasets.

![Image](https://github.com/user-attachments/assets/f2311602-822f-4954-8760-b33c1aed4209)

**Comment by HawkQing1** [comment]
@epamLDadayan, currently we can only support to edit follow fields of specific datasets of specific source, please verify it on main.
git: username, password
confluence: api key, username, token
qtest: api key
bdd loader: username, password

**Comment by epamLDadayan** [comment]
CHecked on Main env, fixed.
