### ISSUE TITLE
[BUG]Prompts-The save button activates when switching between Chat and Completion, even without changes.

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#536]
**Steps to reproduce:**
1. User creates a prompt with all the required properties.
2. User simultaneously switches between Chat and Completion modes.
3. Observe that after each mode switch, the Save button becomes activated.

**Expected result:**
The Save button should only activate when there are unsaved changes to the prompt.

**Actual result:**
The Save button becomes activated after every switch between Chat and Completion modes, even if the user has not made any changes to the prompt.

See attached demo

**Comment by HawkQing1** [comment]
This is designed behavior. So I close it.
