### ISSUE TITLE
[BUG]"Datasource Forking Shows Success but Fails on Backend"

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#539]
**Description:** 
When attempting to fork a Confluence Datasource into another project using API token/secret for authentication, the operation fails on the backend. This occurs even though the frontend displays a success message.

**Steps to Reproduce:**

1. Navigate to the "Create Datasource" page.
2. For the dataset, select "Confluence".
3. Create Secret for Confluence
4. Enter all required configurations.
5. Select the Secret option for the API key authentication.
6. Click on "Fork" and choose the target Project where the Datasource should be forked.
7. Ensure that an API token/secret has already been created in the chosen project.
8. Select "Secret" as the Auth Method.
9. Click on "Fork" to initiate the forking process.

 **Expected Result:** 
Datasource should be successfully forked to the selected Project without any errors, with both frontend and backend systems in agreement.

**Actual Result:**
The UI displays a success message, but the backend logs indicate a failure, and the datasource is not forked to the selected project.

See attached demo

**Comment by HawkQing1** [comment]
Two issues about forking datasource API:

1. the request has token for confluence source dataset, BE still raises token error
2. the error message is located in result instead of errors

**Comment by HawkQing1** [comment]
@epamLDadayan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Fixed, there is another issue related to the bug, in separate ticket 
https://github.com/orgs/ProjectAlita/projects/3/views/1?pane=issue&itemId=88123453&issue=ProjectAlita%7Cprojectalita.github.io%7C551
