### ISSUE TITLE
[BUG] Variables in Prompts assistant messages are exported and forked as text

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#543]
**Precondition:**
A prompt exists with variables in "System", "Assistant" and "User" messages 
![Image](https://github.com/user-attachments/assets/effaecd1-2de8-48dd-ade4-91600b8f745e)

**Steps to reproduce:**
Export the prompt or fork the prompt 

**Actual results:**
1. In the exported JSON, no variables exist, only text 
![Image](https://github.com/user-attachments/assets/7e54e76c-6c2e-4652-b7dd-0a593fba2467)

2. After forking, no variable fields are created 

**Expected results:**
In exported JSON, variables exist 
after forking, variable fields are created 

OR 
Alita will create a variable field using the assistant message text in the JSON

**Comment by plageat** [comment]
Can reproduce it when forking prompt with multiple vars.
Works good for simple import

**Comment by SamvelSimonyan** [comment]
Verified on main
