### ISSUE TITLE
[BUG] Data source storage remains original despite changing upon fork

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#547]
**Precondition:**
A data source is available with ( e.g. pgvector )storage type 

**Steps to reproduce:**
Fork the data source 
Select another storage (e.g. chroma)

**Actual results:**
Datasource is forked with the original (pgvector ) storage type 
![Image](https://github.com/user-attachments/assets/b47cd9c9-edf8-40a8-a178-2787360011b0)

**Expected results:**
Datasource is forked with the selected storage type 

**other info** 
Not sure if it is FE or BE issue 
was not able to find common storage id in the request
![Image](https://github.com/user-attachments/assets/cc4cb3ae-785c-4f1d-8fd1-7e2ae3c1d72a)

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
verified
