### ISSUE TITLE
[BUG]-New Secrets Not Visible in Agent Tool Without Full Page Refresh

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#549]
**Steps to Reproduce:**

1. Navigate to the Agent creation page.
2. Begin the process of setting up a new agent and add an agent tool to it.
3. Open a new browser tab and go to the Secrets creation page.
4. Create a new secret intended for use in the aforementioned agent tool.
5. Return to the Agent creation tab.
6. Attempt to select the newly created secret within the agent tool's configuration options.

**Expected Result:** The newly created secret should be selectable from a dropdown or list within the agent tool's configuration options without needing to refresh the page.

**Actual Result:** The newly created secret is not visible or available for selection within the agent tool's configuration options unless the entire webpage is refreshed.

**Comment by HawkQing1** [comment]
@liana-gif this is not a bug, two tabs can not share the data in memory.
