### ISSUE TITLE
[BUG]-For import and fork actions, all agent tools requiring authentication must be displayed for selection or modification in Fork properties Modal window.

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#550]
**Description:**
When a user initiates a fork of Azure DevOps (ADO) or GitLab tool or Rally tool that is linked to an Agent, the expected authentication methods are not being displayed on the Fork Properties page.

**Steps to Reproduce:**

1. Link an ADO or GitLab tool to an Agent.
2. Proceed to fork the linked repository.
3. On the Fork Properties page, observe that the authentication methods are not shown.

**Expected Result:** The user should be able to see and select from the available authentication methods on the Fork Properties page when forking a repository.

**Actual Result:** Authentication methods are not displayed on the Fork Properties page, leaving the user unable to select or change them.
![Image](https://github.com/user-attachments/assets/0928bcd1-cf4d-41df-9f5c-2be16781d58d)
![Image](https://github.com/user-attachments/assets/885184af-7fb9-4571-98ea-28e535eec15f)

**Comment by HawkQing1** [comment]
@liana-gif it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Not fixed for Rally tool 
![Image](https://github.com/user-attachments/assets/0fbea88d-2f3c-423d-b316-277ff5f3413c)

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
verified for 
Browser 
confluence 
GitHub
GitLab
bitbucket
jira
openAPI
testRail
Ado
qtest

**Comment by SamvelSimonyan** [comment]
Reproduces for Rally tool when importing and forking 
![Image](https://github.com/user-attachments/assets/602395c1-2de4-463d-bd8f-b5129ac289c6)

**Comment by SamvelSimonyan** [comment]
verified on main
