### ISSUE TITLE
[BUG] Inconsistency in naming conventions with resources

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#554]
Description 
For Conversations and collections, spaces are removed from FE side but preserved on Be side 
For Prompts agents and datastores , spaces are not removed on FE side

**Steps to reproduce:**
Create a prompt or agent or datastores using multiple spaces 
Create Conversations (Chat) and collections using multiple spaces 
**Actual results:**
In prompt or agent or datastores the spaces are displayed in FE 
In Conversations (Chat) and collections, spaces exist in BE but are not displayed in FE 
**Expected results:**
The space displayed is consistent with overall resources 
(In Conversations (Chat) and collections, spaces are displayed )

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's fixed, please verify it on main.

**Comment by SamvelSimonyan** [comment]
Not fixed for chat (Conversations)

**Comment by HawkQing1** [comment]
@SamvelSimonyan I've fixed the collapsed white space issue of participant name. Please verify it one more time.

**Comment by SamvelSimonyan** [comment]
Conversations are saved with multiple spaces in DB but are displayed without spaces 
Agents and prompts in the conversation participant sections are displayed without spaces 

We can ignore them for now

**Comment by SamvelSimonyan** [comment]
Verified on main
