### ISSUE TITLE
[BUG] OpenApi tool can't be saved with non auth

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#558]
**Steps to reproduce:**
Create an Open Api toolkit in the agent 
Leave the Auth option as "none"
click the back arrow to go to the agent page 

**Actual results:**
The "Field is not filled" message will be displayed 
![Image](https://github.com/user-attachments/assets/878cf3ae-8a53-4ac9-827a-2b2a5ab0d21b)

**Expected results:**
user can save the tool with the None option 

Other info 
If the tool is saved with another auth option, it can be edited and the None option can be selected successfully

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Verified on main
