### ISSUE TITLE
[BUG] Extra space in secret page when changing drop down list value from 100 items to other value

### ISSUE THREAD

**Issue by RuzanMarutyan** [ProjectAlita/projectalita.github.io#560]
**Precondition:** 
User has more then 10 secrets.

**Steps:**
1. Navigate to the secret section.
2. From the dropdown list, choose 5 or 10 items.

**Expected Result:**
Only 5 rows should be displayed in the secret page.

**Actual Result:**
When choosing 5 items instead of the previous 100, an extra space is visible on the secret page.

**Environment:**
URL: https://eye.projectalita.ai/main/

**Attachments:**
![Image](https://github.com/user-attachments/assets/41587bb2-40d9-409f-bfd5-b8c2a2433fdf)

**Comment by HawkQing1** [comment]
@RuzanMarutyan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Verified on main
