### ISSUE TITLE
[BUG] Tool's secret is passed to forked agent in case we don't have UI for tool configs

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#563]
**Precondition:**
A tool is available with no UI configs when forking ( we have this when adding new tools but did not managed to add UI for fork)

**Steps to reproduce:**
Fork tool 

**Actual results:**
The secret is passed to the forked agent
![Image](https://github.com/user-attachments/assets/825f2b60-133a-404d-9e43-c0aae7c57e38)
![Image](https://github.com/user-attachments/assets/b23b0715-21ff-4db1-b890-33d40e437ac2)

**Expected results:**
secret is not passed to the new agent even if we don't show configs on UI when forking

**Comment by HawkQing1** [comment]
The secret fields should be cleared up when BE exports it for importing/forking. This issue is part of #567.

**Comment by plageat** [comment]
Fixed
See also https://github.com/ProjectAlita/projectalita.github.io/issues/593

**Comment by SamvelSimonyan** [comment]
can't be verified as the Rally forking modal was created
