### ISSUE TITLE
[BUG] Empty secret field when forking tools

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#567]
Precondition 
There is an agent with tools and secrets in it 

**Steps** 
Fork the agent 
Observe the secret field in the fork Modal 
Complete the fork without changing the secret 
Observe the secret filled for forked tool

**Actual result** 
The secret field is not empty in the Fork modal 
The  secret field is not empty for the Forked tool
![Image](https://github.com/user-attachments/assets/d93e20db-e0c2-4583-a316-c87ae635cb4e)

**Expected result** 
The secret field is empty in the Fork modal 
The  secret field is empty for the Forked tool

**Comment by plageat** [comment]
Fixed
See also https://github.com/ProjectAlita/projectalita.github.io/issues/593

**Comment by SamvelSimonyan** [comment]
verified on main
