### ISSUE TITLE
[BUG] Browser toolkit usage will result error

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#568]
**Steps to reproduce:**
Use any tool  from the browser toolkit

**Actual results:**
Agent exception will be displayed 
![Image](https://github.com/user-attachments/assets/82135850-8714-4d30-8e03-cb4a22865857)

**Expected results:**
The tool will provide results

**Comment by MikalaiB** [comment]
Resolved with alita-tools 0.1.4
Deployed to dev env.
