### ISSUE TITLE
[BUG] Agent name field value getting removed after navigating back from toolkit

### ISSUE THREAD

**Issue by RuzanMarutyan** [ProjectAlita/projectalita.github.io#569]
**Preconditions:**
1. Agent configuration is created, name and description fields are filled in.
2. Jira toolkit is created.

**Steps:**
From the Jira toolkit, navigate back to the agent configuration page.

**Expected Result:** 
The agent configuration page should display both the name and description fields with their respective values intact.

**Actual Result:**
 The name field is empty, while the description field retains its value.

**Environment:**
URL: https://eye.projectalita.ai/main/

**Attachments:**
https://github.com/user-attachments/assets/b7620dbe-1c92-435c-9a81-b1a11f6834a6

**Comment by HawkQing1** [comment]
@RuzanMarutyan it's fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
Verified on main
