### ISSUE TITLE
[BUG]ADO Wiki Agent Toolkit: Error Encountered in Retrieving and Deleting Subpages

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#576]
**Description:** When attempting to utilize the 'get by path' and 'delete by path' functions within the ADO Wiki Agent Toolkit to manage subpages, users are experiencing issues. The toolkit is failing to properly retrieve or delete subpages under a Wiki page.

**Steps to Reproduce:**

1. Configure the ADO Wiki Agent Toolkit within Alita Agents.
2. Choose an ADO wiki page that contains one or more subpages.
3. Attempt to retrieve a specific subpage's details using the 'get by path' function from the configured toolkit.
4. Attempt to delete a subpage using the 'delete by path' function from the configured toolkit.

**Expected Result:**

User should successfully retrieve details of the subpage using the 'get by path' function.
User should be able to delete the subpage using the 'delete by path' function with no errors.

**Actual Result:**

The 'get by path' function does not successfully pull details from the subpage.
The 'delete by path' function fails to delete the subpage, potentially resulting in an error message.
See attached screenshots
![Image](https://github.com/user-attachments/assets/45529ef6-ff85-4972-a24e-5ecef7c842dc)
![Image](https://github.com/user-attachments/assets/96add8d6-9449-4225-b0e9-19b5680ff257)

**Comment by liana-gif** [comment]
Not a bug, configuration issue need to provide path like get pages from wiki `TestProject.wiki` by path `Default page/ELITEA SUB_PAGE`

**Comment by MikalaiB** [comment]
Closing it as not an issue.
