### ISSUE TITLE
[BUG] Socket state indicator is not updated when connection is lost

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#585]
**Steps to reproduce:**
Go to a resource 
Set connection to offline from the browser 
Type something in the chat 

**Actual results:**
The socket connection icon is green
Connection attempts are falling 
https://github.com/user-attachments/assets/fad3db9f-e478-439e-ad21-1e085cd9cbca

**Expected results:**
The socket connection icon gets red after the connection error 

**Other info**
The socket icon is updated in case a change is done on UI  ( a dropdown is changed etc )

**Comment by HawkQing1** [comment]
@SamvelSimonyan  it's been fixed, please verify it on main.

**Comment by SamvelSimonyan** [comment]
Verified on main
