### ISSUE TITLE
[BUG]When user fork agent with bitbucket toolkit, then password must not fill in

### ISSUE THREAD

**Issue by liana-gif** [ProjectAlita/projectalita.github.io#593]
**Steps to Reproduce:**

1. Start the Bitbucket toolkit which utilizes a password as the authentication method.
2. Initiate the forking process for an agent.
3. Select the desired project to fork.

**Actual Result:** 
During the forking process, the password field is automatically filled without user intervention.

**Expected Result:** 
The password field should remain empty during the forking process. The user should manually enter their password to ensure secure authentication.
![Image](https://github.com/user-attachments/assets/9afa53e0-d463-47c6-a15a-2c0d40c98fb6)
**NOTE:
Issue was reproducible for Report portal, Zephyr will check for other tools also**

**Comment by plageat** [comment]
Fixed in https://github.com/ProjectAlita/applications/commit/16d4567c5c435bb2cfbcbecc031f42dd8ac42135

Now all sensitive fields in tools settings should be empty

**Comment by plageat** [comment]
Deployed in main

**Comment by liana-gif** [comment]
Verified
