### ISSUE TITLE
[Bug] List_pull_request_files tool will result an error on Github

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#599]
**Precondition:**
The user has an open pull request in github 
Github  agent is configured 

**Steps to reproduce:**
ask the agent "Using List_pull_request_files tool List #1 pull request files"

**Actual results:**
Error is thrown 
![Image](https://github.com/user-attachments/assets/98d00a84-8a4b-48e5-ba6a-9a19c0e8af9e)
e.g.
https://eye.projectalita.ai/main/alita_ui/agents/all/4?viewMode=owner&name=Github+Tester+%5Bissue%5D
agent with "Using List_pull_request_files tool List pull request files for #1 PR" prompt 

**Expected results:**
the tool is executed successfully

**Comment by plageat** [comment]
The error is pretty clear here

Probably need to update both **GetPR** and **GetIssue**

**Comment by SamvelSimonyan** [comment]
Verified on main
