### ISSUE TITLE
[BUG] "Create PR change comment" tool will result an error on Githlab

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#603]
Precondition:
The user has an open pull request in githlab
Githlab agent is configured

**Steps to reproduce:**
Ask the agent to Create PR change comment 
e.g. "using the "Create PR change comment " tool create a random comment on a PR, use all other necessary tools to create the comment. " 
Anget -  https://eye.projectalita.ai/main/alita_ui/agents/all/8?viewMode=owner&name=Gitlab%20Agent

**Actual results:**
the operation will fail 
![Image](https://github.com/user-attachments/assets/fb01c96e-08b4-40cc-98f2-7d0d08602ed4)

**Expected results:**
a PR change comment is created

**Comment by SamvelSimonyan** [comment]
prompt - using "Create PR change comment " tool create a random comment on a PR, use all other necessary tools to create the comment in line 1

**Comment by MikalaiB** [comment]
Make sure agent is aware of:
pr_number
file_path
line_number
comment

If anything is missed or line number is 0 - the comment won't added.
