### ISSUE TITLE
[BUG] Hosting option is not sent to BE when changing to manual config

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#604]
**Steps to reproduce:**
Create a Jira or confluence agent tool using configurations and save it 
change tool from configuration to manual  ( cloud option is selected as hosting option )
fill other fields without touching the hosting option 
save the agent 

**Actual results:**
Agent is not saved with 400 error  ( as hosting option is not passed to BE)
![Image](https://github.com/user-attachments/assets/f3b3395f-21cf-4f9f-a9ff-9a014e6a4c8c)

**Expected results:**
hosting option is passed to BE and the agent is saved with the hosting option displayed on the screen

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's been fixed, please verify it on main

**Comment by SamvelSimonyan** [comment]
verified on main
