### ISSUE TITLE
[BUG] Confluence Create_pages tool will result an error

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#605]
**Steps to reproduce:**
Use the Create_pages tool for confluence 

**Actual results:**
Agent exception will accrue 
![Image](https://github.com/user-attachments/assets/b5e98b1b-97bd-459c-980c-afbab92e571d)

agent e.g. 
https://eye.projectalita.ai/main/alita_ui/agents/all/53?viewMode=owner&name=Confluence_Cloud%20%5BIssue%5D

**Expected results:**
Tool is executed

**Comment by MikalaiB** [comment]
Fixed in tools 0.1.16 - deployed to main

**Comment by SamvelSimonyan** [comment]
verified on main
