### ISSUE TITLE
[BUG] Artifact retention settings change issues

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#609]
**Steps to reproduce:**
Go to Artifacts 
Change retention date of an artifact 
Save it 
Click the edit button

**Actual results:**
Retention settings are null
![Image](https://github.com/user-attachments/assets/29b20aeb-9379-4b88-99be-9d9cdb0ac741)

**Expected results:**
Retention settings are displayed 

**Other info** 
Not sure in which format they must be displayed 
e.g. 
when we user puts 12 m , on ui it will show 1 year ,
 in case 11 m on ui it will show  335 d

**Comment by SamvelSimonyan** [comment]
not sure if it is a bug  @HawkQing1

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's been fixed on main, please verify it.

**Comment by SamvelSimonyan** [comment]
verified on main
