### ISSUE TITLE
[BUG] Artifact create button can lead to edit  popup 

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#610]
**Steps to reproduce:**
1. Go to artifacts 
2. click edit artifacts 
3. click cancel
4. click + icon 

**Actual results:**
Edit artifact window is opened 
https://github.com/user-attachments/assets/6528c0fc-c780-4319-9926-118b8df20e1a

**Expected results:**
+ button opens new bucket window

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's been fixed on main, please verify it on main.

**Comment by SamvelSimonyan** [comment]
verified on main
