### ISSUE TITLE
[BUG] validation issues with Artifacts

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#613]
**Steps to reproduce:**
Go to artifacts and create an artifact with more than 56 chars on the UI 
Or 
Input a number with a lot of chars in retention value when editing
Or 
go to Agent-> Artifact tool and input not valid bucket name ( starting with number or containing other chars ) 
**Actual results:**
No FE validation is checked 
error messages appear after saving or after using the tool 
![Image](https://github.com/user-attachments/assets/e6182674-e4dd-438d-bcc8-9f08fe223df2)
![Image](https://github.com/user-attachments/assets/ea72becb-1651-4709-a7f2-40f9032ed6de)
![Image](https://github.com/user-attachments/assets/d99bd74a-aa68-48c5-884c-c4b2bfe425d8)

**Expected results:**
FE validation is applied on Artifact create/ edit pop up' s for retention setting and bucket name length 
FE validation is applied to the folder name  inside Artifact tool corresponding to the artifact name validation

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's been fixed on main, please verify it on main.

**Comment by SamvelSimonyan** [comment]
verified on main 
small issue - ignored 
![Image](https://github.com/user-attachments/assets/6f5ec209-5eaa-4220-9aa9-5e15aabc0c5c)
cc @HawkQing1
