### ISSUE TITLE
[BUG] Sonar tool will result error when executed

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#620]
**Precondition:**
The agent is configured with a sonar tool

**Steps to reproduce:**
Submit a request 

**Actual results:**
Agent exception is displayed 
![Image](https://github.com/user-attachments/assets/59901add-4c78-487d-9b42-e591339549f8)

agent  e.g. https://eye.projectalita.ai/main/alita_ui/agents/all/58?viewMode=owner&name=Sonar%20%5BIssue%5D
data in Agent 
![Image](https://github.com/user-attachments/assets/08479e02-ccb9-4bf8-a66c-ed308c31c128)

**Expected results:**
data is received

**Comment by MikalaiB** [comment]
Fixed UI, should work.

**Comment by SamvelSimonyan** [comment]
verified on main
