### ISSUE TITLE
[BUG] SQL tool will result error when executed

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#621]
**Precondition:**
The agent is configured with a sql tool

**Steps to reproduce:**
Submit a request 

**Actual results:**
Agent exception is displayed 
![Image](https://github.com/user-attachments/assets/69ef916e-4961-499b-8b6d-2f7fc806b763)

agent  https://eye.projectalita.ai/main/alita_ui/agents/all/57?viewMode=owner&name=SQL+%5B+issue+%5D

**Expected results:**
request is executed

**Comment by MikalaiB** [comment]
Fixed tools and released new version.
it is already deployed to main.

**Comment by SamvelSimonyan** [comment]
verified on main
